// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfgsan0bdHHXYZ6967DeK_Dzzq8A-OEa8',
    appId: '1:875471046066:android:9f032dfb6ce3cf6a1f10ab',
    messagingSenderId: '875471046066',
    projectId: 'unifoodflutter-d2d61',
    storageBucket: 'unifoodflutter-d2d61.appspot.com',
    databaseURL: 'https://unifoodflutter-d2d61-default-rtdb.europe-west1.firebasedatabase.app', // Modifica questa riga per la regione corretta.
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVrUYY-70VeEqpBLNeV1mm662hJ49mlU8',
    appId: '1:875471046066:ios:d33e97cf519f78c61f10ab',
    messagingSenderId: '875471046066',
    projectId: 'unifoodflutter-d2d61',
    storageBucket: 'unifoodflutter-d2d61.appspot.com',
    iosClientId: '875471046066-s01i5hc21i56kmknh6s48mcsadtbt80r.apps.googleusercontent.com',
    iosBundleId: 'com.example.unifood',
  );
}
